language: cpp

sudo: required
dist: trusty

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - libgsl0-dev
      - zlib1g-dev
      - libcmocka-dev
      - libhdf5-dev

script:
  - cmake --version
  - cd kwip2
  - rm -rf build && mkdir build
  - pushd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make VERBOSE=1
  - ./bin/kwip_tests -v
  - popd
