language: cpp

env:
 matrix:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - python-sphinx

install:
- export CXX="g++-4.8" CC="gcc-4.8"

script:
 - bash .biojenkins-build.sh
