language: cpp

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug
    - KWIPY=yes

sudo: required
dist: trusty

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblzo2-dev liblz4-dev libsnappy-dev libbz2-dev
                            libhdf5-dev
  - sudo apt-get install -y python3-pip
  - pip3 install --user sphinx>=1.3

script:
  - if [ -z "$KWIPY" ] ; then
      bash util/ci-build.sh;
    else
      cd kwipy && bash .ci.sh;
    fi
