language: cpp

sudo: required
dist: trusty

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

compiler:
  - gcc

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install --user sphinx>=1.3

script:
  - bash util/ci-build.sh
