language: cpp

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug
    - KWIPY=yes

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install python3-pip
  - pip3 install --user sphinx>=1.3

script:
  - if [ -z "$KWIPY" ] ; then
      bash util/ci-build.sh;
    else
      cd kwipy && bash .ci.sh;
    fi
