language: cpp

sudo: required
dist: trusty

env:
  matrix:
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug

compiler:
  - gcc

addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - libgsl0-dev
      - zlib1g-dev
      - libhdf5-dev

before_install:
  - wget -O cmocka.tar.xz https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
  - tar -xvf cmocka.tar.xz
  - cd cmocka-*
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - sudo make install
  - cd ../..
  - rm -rf cmocka*


script:
  - cmake --version
  - cd kwip2
  - rm -rf build && mkdir build
  - pushd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make VERBOSE=1
  - ./bin/kwip_tests -v
  - popd
